a.out:	bplus.c
	cc bplus.c
	./a.out<input1.txt
	dot -Tpng opb+.dot>opbplus.png
	eog opbplus.png
	./a.out<input2.txt
	dot -Tpng opb+.dot>opbplus.png
	eog opbplus.png
	./a.out<input3.txt
	dot -Tpng opb+.dot>opbplus.png
	eog opbplus.png
	./a.out<input4.txt
	dot -Tpng opb+.dot>opbplus.png
	eog opbplus.png
	./a.out<input5.txt
	dot -Tpng opb+.dot>opbplus.png
	eog opbplus.png
	./a.out<input6.txt
	dot -Tpng opb+.dot>opbplus.png
	eog opbplus.png
	./a.out<input7.txt
	dot -Tpng opb+.dot>opbplus.png
	eog opbplus.png
	./a.out<input8.txt
	dot -Tpng opb+.dot>opbplus.png
	eog opbplus.png
	./a.out<input9.txt
	dot -Tpng opb+.dot>opbplus.png
	eog opbplus.png
	./a.out<input10.txt
	dot -Tpng opb+.dot>opbplus.png
	eog opbplus.png
