a.out:	bplus.c
	cc bplus.c
	./a.out<input1.txt
	dot -Tps opb+.dot>opbplus.ps
	eog opbplus.ps
	./a.out<input2.txt
	dot -Tps opb+.dot>opbplus.ps
	eog opbplus.ps
	./a.out<input3.txt
	dot -Tps opb+.dot>opbplus.ps
	eog opbplus.ps
	./a.out<input4.txt
	dot -Tps opb+.dot>opbplus.ps
	eog opbplus.ps
	./a.out<input5.txt
	dot -Tps opb+.dot>opbplus.ps
	eog opbplus.ps
