all:
	cc avl.c
	./a.out < input1.txt
	dot -Tpng opavl.dot > opavl.png
	eog opavl.png
	./a.out < input2.txt
	dot -Tpng opavl.dot > opavl.png
	eog opavl.png
	./a.out < input3.txt
	dot -Tpng opavl.dot > opavl.png
	eog opavl.png
	./a.out < input4.txt
	dot -Tpng opavl.dot > opavl.png
	eog opavl.png
	./a.out < input5.txt
	dot -Tpng opavl.dot > opavl.png
	eog opavl.png
